export const openApiDocument = {
  openapi: "3.1.0",
  info: { title: "AgentHub Local Daemon API", version: "0.1.0" },
  paths: {
    "/healthz": { get: { summary: "Daemon health" } },
    "/event": { get: { summary: "SSE stream with durable replay and live events" } },
    "/rooms": { get: { summary: "List rooms" }, post: { summary: "Create solo or assisted room through CommandBus" } },
    "/rooms/{roomId}": { get: { summary: "Read room" } },
    "/rooms/{roomId}/archive": { post: { summary: "Archive room through CommandBus" } },
    "/rooms/{roomId}/unarchive": { post: { summary: "Unarchive room through CommandBus" } },
    "/rooms/{roomId}/messages": { get: { summary: "List messages" }, post: { summary: "Send user message through CommandBus" } },
    "/messages/{messageId}": { delete: { summary: "Delete message through CommandBus" } },
    "/agents": { get: { summary: "List agent profiles" } },
    "/agents/{agentId}": { get: { summary: "Read agent profile" } },
    "/runs/{runId}": { get: { summary: "Read run detail" } },
    "/context": { get: { summary: "List context items" } },
    "/context/propose": { post: { summary: "Propose draft context through CommandBus" } },
    "/context/write": { post: { summary: "Write context through trusted-tool ledger guard via CommandBus" } },
    "/context/{contextId}": { patch: { summary: "Update context with optimistic version through CommandBus" } },
    "/context/{contextId}/confirm": { post: { summary: "Confirm draft context through CommandBus" } },
    "/context/{contextId}/deprecate": { post: { summary: "Deprecate context through CommandBus" } },
    "/context/{contextId}/pin": { post: { summary: "Pin context to workspace scope through CommandBus" } },
    "/permissions/profiles": { get: { summary: "List permission profiles" }, post: { summary: "Create permission profile through CommandBus" } },
    "/permissions/profiles/{profileId}": { get: { summary: "Read permission profile" }, patch: { summary: "Patch permission profile through CommandBus" } },
    "/permissions/requests": { get: { summary: "List permission requests" } },
    "/permissions/{requestId}/resolve": { post: { summary: "Resolve permission request through CommandBus" } },
    "/permissions/rules": { get: { summary: "List permission rules" } },
    "/permissions/rules/{ruleId}": { delete: { summary: "Delete permission rule through CommandBus" } },
    "/interventions": { get: { summary: "List interventions" }, post: { summary: "Request intervention through CommandBus" } },
    "/interventions/{interventionId}": { get: { summary: "Read intervention" } },
    "/interventions/{interventionId}/approve": { post: { summary: "Approve intervention through CommandBus" } },
    "/interventions/{interventionId}/ignore": { post: { summary: "Ignore intervention through CommandBus" } },
    "/interventions/{interventionId}/reject": { post: { summary: "Reject intervention through CommandBus" } },
    "/interventions/{interventionId}/later": { post: { summary: "Snooze intervention through CommandBus" } },
    "/artifacts": { get: { summary: "List artifacts" }, post: { summary: "Create artifact through CommandBus" } },
    "/artifacts/{artifactId}": { get: { summary: "Read artifact" } },
    "/artifacts/{artifactId}/review": { post: { summary: "Move diff artifact to reviewing through CommandBus" } },
    "/artifacts/{artifactId}/apply": { post: { summary: "Accept and apply diff artifact through CommandBus" } },
    "/artifacts/{artifactId}/reject": { post: { summary: "Reject diff artifact through CommandBus" } },
    "/artifacts/{artifactId}/revert": { post: { summary: "Create reverse diff artifact through CommandBus" } },
    "/artifacts/{artifactId}/files": { get: { summary: "List artifact files" } },
    "/artifacts/{artifactId}/files/{path}": { get: { summary: "Read artifact file content" } },
    "/debug/events": { get: { summary: "Query durable events for debug replay" } },
    "/debug/stats": { get: { summary: "Read daemon debug counters" } }
  }
} as const;
